name: Build and deploy dagpenger

on:
  push:
    branches:
      - main
    paths:
      - dagpenger/**
      - felles/**
      - config/dagpenger/**
      - Dockerfile
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
      - gradle/**
  schedule:
    - cron: '0 9 * * 3'
      timezone: 'Europe/Oslo'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      has_app_jar: ${{ steps.app_jar.outputs.files_exists }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: cache gradle wrapper
        uses: actions/cache@v5
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle caches
        uses: actions/cache@v5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: test and build
        run: ./gradlew dagpenger:test dagpenger:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check app.jar existence
        id: app_jar
        uses: andstor/file-existence-action@v3
        with:
          files: dagpenger/build/libs/app.jar
      - name: build docker image
        if: steps.app_jar.outputs.files_exists == 'true'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: dagpenger
          dockerfile: Dockerfile
          docker_context: dagpenger

  deploy-dev:
    needs: build
    if: needs.build.outputs.has_app_jar == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Fetch sources
        uses: actions/checkout@v7
      - name: Ensure deploy files exist
        id: deploy-files
        uses: andstor/file-existence-action@v3
        with:
          files: config/dagpenger/dev-gcp.yml
      - name: deploy
        if: steps.deploy-files.outputs.files_exists == 'true'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: config/dagpenger/dev-gcp.yml
          IMAGE: ${{ needs.build.outputs.image }}

  deploy-prod:
    needs: [build, deploy-dev]
    if: needs.build.outputs.has_app_jar == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Fetch sources
        uses: actions/checkout@v7
      - name: Ensure deploy files exist
        id: deploy-files
        uses: andstor/file-existence-action@v3
        with:
          files: config/dagpenger/prod-gcp.yml
      - name: deploy
        if: steps.deploy-files.outputs.files_exists == 'true'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: config/dagpenger/prod-gcp.yml
          IMAGE: ${{ needs.build.outputs.image }}

